### ISSUE TITLE
 Self hosted giscus error :  "fetch failed"

### ISSUE THREAD

**Issue by deep9699** [giscus/giscus#1305]
Have Self hosted giscus on [https://self-host-giscus.vercel.app/](https://self-host-giscus.vercel.app/) and try to get script if i type any random repo in the api then it returns error that giscus is not installed in this repo which is right but when i enter the repo name for which self hosted giscus is installed it throws an error 

{error : "fetch failed"} 

even when try to run build in local it throws fetch error

Error occurred prerendering page "/en". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: fetch failed
    at Object.fetch (node:internal/deps/undici/undici:11730:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 1)
    at async getStaticProps (D:\Learning\Docusaurus\giscus\.next\server\pages\index.js:972:43)
    at async __Next_Translate__getStaticProps__18d354bdc4d__ (D:\Learning\Docusaurus\giscus\.next\server\pages\index.js:1124:17)
    at async renderToHTML (D:\Learning\Docusaurus\giscus\node_modules\next\dist\server\render.js:386:20)
    at async D:\Learning\Docusaurus\giscus\node_modules\next\dist\export\worker.js:304:36
    at async Span.traceAsyncFn (D:\Learning\Docusaurus\giscus\node_modules\next\dist\trace\trace.js:79:20)

info  - Generating static pages (5/5)

> Build error occurred
Error: Export encountered errors on following paths:
        /: /en
    at D:\Learning\Docusaurus\giscus\node_modules\next\dist\export\index.js:404:19
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Span.traceAsyncFn (D:\Learning\Docusaurus\giscus\node_modules\next\dist\trace\trace.js:79:20)
    at async D:\Learning\Docusaurus\giscus\node_modules\next\dist\build\index.js:1230:21
    at async Span.traceAsyncFn (D:\Learning\Docusaurus\giscus\node_modules\next\dist\trace\trace.js:79:20)
    at async D:\Learning\Docusaurus\giscus\node_modules\next\dist\build\index.js:1092:17
    at async Span.traceAsyncFn (D:\Learning\Docusaurus\giscus\node_modules\next\dist\trace\trace.js:79:20)
    at async Object.build [as default] (D:\Learning\Docusaurus\giscus\node_modules\next\dist\build\index.js:65:29)
error Command failed with exit code 1.

**Comment by laymonage** [comment]
Might be related to #1368.
