### ISSUE TITLE
Build fails to generate static pages

### ISSUE THREAD

**Issue by fredrikfischer** [giscus/giscus#1368]
I'm trying to run Giscus locally on a windows system (and in WSL), but I can not get "yarn build" to function. Both on Windows and in WSL it fails to generate the static pages.

Anyone have any idea on how to solve this or what the issue could be? 

```
Error occurred prerendering page "/da". Read more: https://nextjs.org/docs/messages/prerender-error

TypeError: fetch failed
    at node:internal/deps/undici/undici:12442:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at async q (C:\Users\user\test\giscus\.next\server\pages\index.js:3:60)
    at async R (C:\Users\user\test\giscus\.next\server\pages\index.js:3:2144)
    at async e3 (C:\Users\user\test\giscus\node_modules\next\dist\compiled\next-server\pages.runtime.prod.js:25:3907)
    at async exportPages (C:\Users\user\test\giscus\node_modules\next\dist\export\routes\pages.js:84:28)
    at async exportPageImpl (C:\Users\user\test\giscus\node_modules\next\dist\export\worker.js:205:16)
    at async Span.traceAsyncFn (C:\Users\user\test\giscus\node_modules\next\dist\trace\trace.js:154:20)
    at async Object.exportPage (C:\Users\user\test\giscus\node_modules\next\dist\export\worker.js:236:20)

Error occurred prerendering page "/de". Read more: https://nextjs.org/docs/messages/prerender-error
```

```
Export encountered errors on following paths:
        /: /ar
        /: /ca
        /: /da
        /: /de
        /: /en
        /: /eo
        /: /es
        /: /fa
        /: /fr
        /: /gr
        /: /gsw
        /: /he
        /: /hu
        /: /id
        /: /it
        /: /ja
        /: /kh
        /: /ko
        /: /nl
        /: /pl
        /: /pt
        /: /ro
        /: /ru
        /: /th
        /: /tr
        /: /uk
        /: /uz
        /: /vi
        /: /zh-CN
        /: /zh-Hans
        /: /zh-Hant
        /: /zh-TW
error Command failed with exit code 1.
```

**Comment by laymonage** [comment]
I'm not sure why either. It's probably because an authentication issue with GitHub. I've tried to improve this in #1591 to ensure it uses token from your self-hosted repo (set via `NEXT_PUBLIC_DEMO_REPO`) instead of hardcoded to `giscus/giscus`.
