### ISSUE TITLE
Unexpected token 'I', "Internal S"... is not valid JSON

### ISSUE THREAD

**Issue by LoongmaSpirit** [giscus/giscus#1377]
同样的配置，在 vercel 部署正常后，迁移到 Netlify 时，报错：`Unexpected token 'I', "Internal S"... is not valid JSON`：

![image](https://github.com/giscus/giscus/assets/162437080/6df60548-7446-484b-b99a-5f8b12c31465)

所有的 Env 均已在 Netlify 控制台设置完毕：

![image](https://github.com/giscus/giscus/assets/162437080/b071c4e0-7e31-424c-af2b-b5a8828b6dce)

**Comment by LoongmaSpirit** [comment]
本地 debug，错误信息如下：

```
next-translate - compiled page: /widget - locale: zh-CN - namespaces: common - used loader: getServerSideProps
TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Access-Control-Allow-Origin"
    at ServerResponse.setHeader (node:_http_outgoing:655:3)
    at _res.setHeader (C:\Workspace\giscus\node_modules\next\dist\server\base-server.js:127:24)
    at addCorsHeaders (C:\Workspace\giscus\.next\server\chunks\3827.js:38:13)
    at DiscussionsApi (C:\Workspace\giscus\.next\server\pages\api\discussions.js:469:35)
    at Object.apiResolver (C:\Workspace\giscus\node_modules\next\dist\server\api-utils\node.js:366:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextNodeServer.runApi (C:\Workspace\giscus\node_modules\next\dist\server\next-server.js:481:9)
    at async Object.fn (C:\Workspace\giscus\node_modules\next\dist\server\next-server.js:741:37)
    at async Router.execute (C:\Workspace\giscus\node_modules\next\dist\server\router.js:252:36) {
  code: 'ERR_HTTP_INVALID_HEADER_VALUE'
}
TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Access-Control-Allow-Origin"
    at ServerResponse.setHeader (node:_http_outgoing:655:3)
    at _res.setHeader (C:\Workspace\giscus\node_modules\next\dist\server\base-server.js:127:24)
    at addCorsHeaders (C:\Workspace\giscus\.next\server\chunks\3827.js:38:13)
    at DiscussionsApi (C:\Workspace\giscus\.next\server\pages\api\discussions.js:469:35)
    at Object.apiResolver (C:\Workspace\giscus\node_modules\next\dist\server\api-utils\node.js:366:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextNodeServer.runApi (C:\Workspace\giscus\node_modules\next\dist\server\next-server.js:481:9)
    at async Object.fn (C:\Workspace\giscus\node_modules\next\dist\server\next-server.js:741:37)
    at async Router.execute (C:\Workspace\giscus\node_modules\next\dist\server\router.js:252:36) {
  code: 'ERR_HTTP_INVALID_HEADER_VALUE'
}
TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Access-Control-Allow-Origin"
    at ServerResponse.setHeader (node:_http_outgoing:655:3)
    at _res.setHeader (C:\Workspace\giscus\node_modules\next\dist\server\base-server.js:127:24)
    at addCorsHeaders (C:\Workspace\giscus\.next\server\chunks\3827.js:38:13)
    at DiscussionsApi (C:\Workspace\giscus\.next\server\pages\api\discussions.js:469:35)
    at Object.apiResolver (C:\Workspace\giscus\node_modules\next\dist\server\api-utils\node.js:366:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextNodeServer.runApi (C:\Workspace\giscus\node_modules\next\dist\server\next-server.js:481:9)
    at async Object.fn (C:\Workspace\giscus\node_modules\next\dist\server\next-server.js:741:37)
    at async Router.execute (C:\Workspace\giscus\node_modules\next\dist\server\router.js:252:36) {
  code: 'ERR_HTTP_INVALID_HEADER_VALUE'
}
TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Access-Control-Allow-Origin"
    at ServerResponse.setHeader (node:_http_outgoing:655:3)
    at _res.setHeader (C:\Workspace\giscus\node_modules\next\dist\server\base-server.js:127:24)
    at addCorsHeaders (C:\Workspace\giscus\.next\server\chunks\3827.js:38:13)
    at DiscussionsApi (C:\Workspace\giscus\.next\server\pages\api\discussions.js:469:35)
    at Object.apiResolver (C:\Workspace\giscus\node_modules\next\dist\server\api-utils\node.js:366:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextNodeServer.runApi (C:\Workspace\giscus\node_modules\next\dist\server\next-server.js:481:9)
    at async Object.fn (C:\Workspace\giscus\node_modules\next\dist\server\next-server.js:741:37)
    at async Router.execute (C:\Workspace\giscus\node_modules\next\dist\server\router.js:252:36) {
  code: 'ERR_HTTP_INVALID_HEADER_VALUE'
}
TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Access-Control-Allow-Origin"
    at ServerResponse.setHeader (node:_http_outgoing:655:3)
    at _res.setHeader (C:\Workspace\giscus\node_modules\next\dist\server\base-server.js:127:24)
    at addCorsHeaders (C:\Workspace\giscus\.next\server\chunks\3827.js:38:13)
    at DiscussionsApi (C:\Workspace\giscus\.next\server\pages\api\discussions.js:469:35)
    at Object.apiResolver (C:\Workspace\giscus\node_modules\next\dist\server\api-utils\node.js:366:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextNodeServer.runApi (C:\Workspace\giscus\node_modules\next\dist\server\next-server.js:481:9)
    at async Object.fn (C:\Workspace\giscus\node_modules\next\dist\server\next-server.js:741:37)
    at async Router.execute (C:\Workspace\giscus\node_modules\next\dist\server\router.js:252:36) {
  code: 'ERR_HTTP_INVALID_HEADER_VALUE'
}
```

**Comment by LoongmaSpirit** [comment]
netfily平台必须配置env.original，否则报错
