### ISSUE TITLE
yarn next export error

### ISSUE THREAD

**Issue by nagaame** [giscus/giscus#461]
An error occurred when I executed this command

```
yarn next export
```
error message
```
$ /Users/xxx/xxx/ghost/giscus/node_modules/.bin/next export
info  - Loaded env from /Users/xxx/xxx/ghost/giscus/.env
info  - using build directory: /Users/xxx/xxx/ghost/giscus/.next
warn  - rewrites, redirects, and headers are not applied when exporting your application, detected (headers). See more info here: https://nextjs.org/docs/messages/export-no-custom-routes
info  - Copying "static build" directory
info  - No "exportPathMap" found in "/Users/xxx/xxx/ghost/giscus/next.config.js". Generating map from "./pages"
Error: i18n support is not compatible with next export. See here for more info on deploying: https://nextjs.org/docs/deployment
    at /Users/xxx/xxx/ghost/giscus/node_modules/next/dist/export/index.js:148:19
    at async Span.traceAsyncFn (/Users/xxx/xxx/ghost/giscus/node_modules/next/dist/trace/trace.js:79:20)
error Command failed with exit code 1.
```

my tools version

yarn 1.22.17
node 12.22.1

**Comment by nagaame** [comment]
I see it all. I will use vercel for self-hosting this project for now. Thanks a lot!
Looking forward to your good news.
