### ISSUE TITLE
500 error when logging into GitHub after successful deployment on Vercel

### ISSUE THREAD

**Issue by nagaame** [giscus/giscus#819]
I recently deployed a project on Vercel, and the deployment was successful. However, when I tried to log into my GitHub account, I received a 500 error. The error message in the log is as follows:
error log

```
[GET] /api/oauth/authorize?redirect_uri=https%3A%2F%2Fkuokuo.io%2F2022%2F10%2F29%2Fuse-fast-tuic-for-your-proxy%2F
16:21:13:16
2022-12-11T08:21:13.769Z	a6faadc2-ca76-4fff-9950-b8424f6b20b7	ERROR	TypeError: Cannot read property 'subtle' of undefined
    at aesGcmEncrypt (/var/task/.next/server/chunks/108.js:33:64)
    at encodeState (/var/task/.next/server/chunks/108.js:88:12)
    at OAuthAuthorizeApi (/var/task/.next/server/pages/api/oauth/authorize.js:38:95)
    at Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:366:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:741:37)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:252:36)
    at async NextNodeServer.run (/var/task/node_modules/next/dist/server/base-server.js:365:29)
2022-12-11T08:21:13.806Z	a6faadc2-ca76-4fff-9950-b8424f6b20b7	ERROR	TypeError: Cannot read property 'subtle' of undefined
    at aesGcmEncrypt (/var/task/.next/server/chunks/108.js:33:64)
    at encodeState (/var/task/.next/server/chunks/108.js:88:12)
    at OAuthAuthorizeApi (/var/task/.next/server/pages/api/oauth/authorize.js:38:95)
    at Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:366:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/var/task/node_modules/next/dist/server/next-server.js:741:37)
    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:252:36)
    at async NextNodeServer.run (/var/task/node_modules/next/dist/server/base-server.js:365:29)
RequestId: a6faadc2-ca76-4fff-9950-b8424f6b20b7 Error: Runtime exited with error: exit status 1
Runtime.ExitError
```

I am not sure what is causing this error, and I would appreciate any help in resolving it. Is there something I can do on my end, or should I contact the Vercel support team for assistance?

**Comment by laymonage** [comment]
Which Node.js version are you using on Vercel?

**Comment by nagaame** [comment]
Oh, yes, when I switched nodejs to the 16.x version, the error disappeared. Thank you.
